env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:astro/recommended

parserOptions:
  ecmaVersion: 2022
  sourceType: module
  extraFileExtensions:
    - ".astro"

overrides:
  - files: "*.astro"
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions: [".astro"]
